[project]
name = "urban-noise-classification"
version = "0.1.0"
description = "Thesis project regarding speeding up urban noise classification"
authors = [{name = "arriburi"}]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "datasets>=4.4.1",
    "ffmpeg>=1.4",
    "laion-clap @ git+https://github.com/LAION-AI/CLAP.git",
    "librosa>=0.10.0",
    "matplotlib>=3.10.8",
    "numpy>=1.26.0,<2.0.0",
    "py-salt @ file:///C:/Users/Luca/Desktop/urban-noise-classification/salt/py-salt",
    "pygraphviz>=1.14; platform_system != 'Windows'",
    "scikit-learn>=1.5.0",
    "soundfile>=0.13.1",
    "torch>=2.4.0,<2.6.0",
    "torchaudio>=2.4.0,<2.6.0",
    "torchvision>=0.15.0,<0.21.0",
    "transformers>=4.51.3",
]

[project.optional-dependencies]
dev = []

[tool.setuptools]
packages = []  # This is a data/script project, not a Python package
